fieldLayouts:
  d9351cdc-c851-4033-9de9-14b113fba509:
    tabs:
      -
        elements:
          -
            instructions: null
            label: ''
            type: craft\fieldlayoutelements\EntryTitleField
          -
            fieldUid: 19e0a2c5-e675-4b45-8d70-1983eed42b14
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: cc9514d4-46fa-4dff-b225-ead0b5471f76
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 654fd8ac-22ad-476c-8d65-e126d8553609
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: ce5255b2-006f-4091-8619-fd4ecd65b470
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: Common
        sortOrder: 1
      -
        elements:
          -
            fieldUid: 7d53de82-4751-47b4-ae8b-a6b8c5c6e02c
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 7ee2b741-9530-4f2a-9190-3b3db19483b4
            required: false
            type: craft\fieldlayoutelements\CustomField
          -
            fieldUid: 616f87de-8628-44c9-95b3-6a72a6292585
            required: false
            type: craft\fieldlayoutelements\CustomField
        name: SEO
        sortOrder: 2
handle: contact
hasTitleField: false
name: Contact
section: 8b0cd0b9-cc3a-44ab-9232-038003dcff32
sortOrder: 1
titleFormat: '{section.name|raw}'
