contentColumnType: string
fieldGroup: ee372277-a14e-4157-8a34-b211bca6618a
handle: contactFormOptions
instructions: ''
name: 'Contact Form Options'
searchable: true
settings:
  columns:
    __assoc__:
      -
        - c026e3a3-d1b5-40f1-b4b4-03c1790b24f1
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 331e9e56-cb1c-4d20-abc4-eb23639b3f8a
        -
          __assoc__:
            -
              - width
              - ''
      -
        - fec75edb-bbd1-45b9-b34c-2589d0dd9a04
        -
          __assoc__:
            -
              - width
              - ''
      -
        - 126363bf-8d7e-47fc-b8ef-b65399d3c146
        -
          __assoc__:
            -
              - width
              - ''
  contentTable: '{{%stc_contactformoptions}}'
  fieldLayout: row
  maxRows: ''
  minRows: ''
  propagationMethod: all
  selectionLabel: ''
  staticField: '1'
translationKeyFormat: null
translationMethod: site
type: verbb\supertable\fields\SuperTableField
