contentColumnType: string
fieldGroup: ee372277-a14e-4157-8a34-b211bca6618a
handle: organizationType
instructions: ''
name: 'Organization Type'
searchable: true
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - State-based
        -
          - value
          - state
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - National
        -
          - value
          - national
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
