contentColumnType: string(640)
fieldGroup: eb163625-fc07-4c73-8e79-9978cead673f
handle: seoDescription
instructions: 'Used for meta description to improve SEO'
name: 'SEO Description'
searchable: true
settings:
  byteLimit: null
  charLimit: 160
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
