contentColumnType: string
fieldGroup: eb163625-fc07-4c73-8e79-9978cead673f
handle: shareImage
instructions: 'Used when sharing a post or page on social'
name: 'Share Image'
searchable: true
settings:
  allowSelfRelations: ''
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:199d7fed-4975-4bfb-9491-54c6733697d0'
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  restrictFiles: '1'
  selectionLabel: 'Add image'
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:199d7fed-4975-4bfb-9491-54c6733697d0'
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: false
  validateRelatedElements: ''
  viewMode: large
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
