field: cc2a1a27-0458-4256-a719-304b113d8723
fieldLayouts:
  e25f9d9f-bf68-40ce-a60a-fa1d8f9e64bc:
    tabs:
      -
        fields:
          6ed63b23-6500-417e-b56c-01a633351784:
            required: false
            sortOrder: 2
          c9a7c5a7-a5e7-423f-82a1-61039473eda2:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  6ed63b23-6500-417e-b56c-01a633351784:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  c9a7c5a7-a5e7-423f-82a1-61039473eda2:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
