field: 154e4580-c9fb-4511-b0e4-dd6871a55f94
fieldLayouts:
  27051ee1-61fe-413f-95d4-a92e6575dfde:
    tabs:
      -
        fields:
          70944f7e-1ffb-4773-b050-e03d05b29a48:
            required: false
            sortOrder: 2
          baf843ec-a853-4d4c-a0cc-cbf68f9b59c0:
            required: false
            sortOrder: 3
          d02f5d5d-6427-4472-b579-585e52597689:
            required: false
            sortOrder: 1
        name: Content
        sortOrder: 1
fields:
  70944f7e-1ffb-4773-b050-e03d05b29a48:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  baf843ec-a853-4d4c-a0cc-cbf68f9b59c0:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  d02f5d5d-6427-4472-b579-585e52597689:
    contentColumnType: text
    fieldGroup: null
    handle: subhead
    instructions: ''
    name: Subhead
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
