field: f6d77802-a17d-4166-9ef6-49c1a2211990
fieldLayouts:
  da3508c3-12c3-4814-9140-d9258e150327:
    tabs:
      -
        fields:
          055ba65e-1e74-43f0-ac37-7667601eb49f:
            required: false
            sortOrder: 3
          36419058-c5ff-4009-9634-ab842c127362:
            required: false
            sortOrder: 2
          59b90a23-5978-4415-b81b-862cf635fa3d:
            required: false
            sortOrder: 1
          ab584a80-604e-49f9-93a0-731a8ee47445:
            required: false
            sortOrder: 4
        name: Content
        sortOrder: 1
fields:
  055ba65e-1e74-43f0-ac37-7667601eb49f:
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: ''
    name: Body
    searchable: true
    settings:
      availableTransforms: '*'
      availableVolumes: '*'
      cleanupHtml: true
      columnType: text
      purifierConfig: ''
      purifyHtml: '1'
      redactorConfig: Simple.json
      removeEmptyTags: '1'
      removeInlineStyles: '1'
      removeNbsp: '1'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
  36419058-c5ff-4009-9634-ab842c127362:
    contentColumnType: text
    fieldGroup: null
    handle: headline
    instructions: ''
    name: Headline
    searchable: true
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '2'
      multiline: '1'
      placeholder: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  59b90a23-5978-4415-b81b-862cf635fa3d:
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: 'If two images are chosen, the second is used for mobile breakpoints'
    name: Image
    searchable: true
    settings:
      allowSelfRelations: ''
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:199d7fed-4975-4bfb-9491-54c6733697d0'
      defaultUploadLocationSubpath: ''
      limit: '2'
      localizeRelations: false
      restrictFiles: '1'
      selectionLabel: 'Add image'
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:199d7fed-4975-4bfb-9491-54c6733697d0'
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: ''
      viewMode: large
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  ab584a80-604e-49f9-93a0-731a8ee47445:
    contentColumnType: text
    fieldGroup: null
    handle: focusAreas
    instructions: ''
    name: 'Focus Areas'
    searchable: true
    settings:
      addRowLabel: 'Add a focus area'
      columnType: text
      columns:
        __assoc__:
          -
            - col1
            -
              __assoc__:
                -
                  - heading
                  - Title
                -
                  - handle
                  - title
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
          -
            - col2
            -
              __assoc__:
                -
                  - heading
                  - Description
                -
                  - handle
                  - description
                -
                  - width
                  - ''
                -
                  - type
                  - singleline
      defaults:
        -
          __assoc__:
            -
              - col1
              - ''
            -
              - col2
              - ''
      maxRows: ''
      minRows: ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Table
