enableVersioning: true
handle: grants
name: Grants
propagationMethod: all
siteSettings:
  0bbdcfe9-e293-43dc-abc6-1fe5b2139880:
    enabledByDefault: true
    hasUrls: true
    template: grants/index
    uriFormat: grants
type: single
