enableVersioning: true
handle: grants
name: Grants
previewTargets:
  -
    __assoc__:
      -
        - label
        - Grants
      -
        - urlFormat
        - grants
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  0bbdcfe9-e293-43dc-abc6-1fe5b2139880:
    enabledByDefault: true
    hasUrls: true
    template: grants/index
    uriFormat: grants
type: single
